spring.application.name=eureka_server
server.port=8761

# Tell the server it doesn't need to register as a client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Optional: Helps with identifying the server in local development
eureka.instance.hostname=localhost