-- ============================================================
-- auth-service dev sample data
-- Re-run safe: INSERT IGNORE skips rows that already exist.
-- BCrypt hashes generated by HashGeneratorTest (cost=10):
--   Admin@123   -> $2a$10$Ee8u1USmvkwCNo5.21SY6.1UqqpI5oGbI2BkSAMjnruzefgeL1IZ2
--   Doctor@123  -> $2a$10$5YN37vvo8ClbvwaXHQTYZeJnOa5/XbKQ2EjvZTiYk5u3noKMi4EyG
--   Patient@123 -> $2a$10$66B24li6VbHSWWaqz.R6luZKyjoyq.ZgdcnJPksxVDtJocsZ8uuVS
-- ============================================================

INSERT IGNORE INTO users (user_id, email, role, service_id, password)
VALUES
  (1, 'admin@hospital.com',          'ADMIN',   NULL, '$2a$10$Ee8u1USmvkwCNo5.21SY6.1UqqpI5oGbI2BkSAMjnruzefgeL1IZ2'),
  (2, 'santhosh123.2004@gmail.com',      'PATIENT', 1,    '$2a$10$66B24li6VbHSWWaqz.R6luZKyjoyq.ZgdcnJPksxVDtJocsZ8uuVS'),
  (3, 'priya.kapoor@gmail.com',      'PATIENT', 2,    '$2a$10$66B24li6VbHSWWaqz.R6luZKyjoyq.ZgdcnJPksxVDtJocsZ8uuVS'),
  (4, 'rahul.verma@gmail.com',       'PATIENT', 3,    '$2a$10$66B24li6VbHSWWaqz.R6luZKyjoyq.ZgdcnJPksxVDtJocsZ8uuVS'),
  (5, 'sandy321.2004@gmail.com',     'DOCTOR',  1,    '$2a$10$5YN37vvo8ClbvwaXHQTYZeJnOa5/XbKQ2EjvZTiYk5u3noKMi4EyG'),
  (6, 'dr.sneha.patel@gmail.com',    'DOCTOR',  2,    '$2a$10$5YN37vvo8ClbvwaXHQTYZeJnOa5/XbKQ2EjvZTiYk5u3noKMi4EyG'),
  (7, 'dr.vijay.menon@gmail.com',    'DOCTOR',  3,    '$2a$10$5YN37vvo8ClbvwaXHQTYZeJnOa5/XbKQ2EjvZTiYk5u3noKMi4EyG');
