spring.application.name=api-gateway
server.port=8090

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.instance-id=${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

