server.port=8086
spring.application.name=notification-service

spring.datasource.url=jdbc:mysql://localhost:3306/notification_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Eureka ? so Feign can discover patient-service and doctor-service by name
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.enabled=false

# Feign timeout settings
feign.client.config.default.connect-timeout=3000
feign.client.config.default.read-timeout=3000

