# 1. Service Identification
spring.application.name=doctor-service
server.port=8084
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:dev-data.sql
spring.sql.init.continue-on-error=true

# 2. Database Connection URL
spring.datasource.url=jdbc:mysql://localhost:3306/doctor_service_database_hams?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true

# 3. Database Username and Password
spring.datasource.username=root
spring.datasource.password=root

# 4. MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 5. JPA/Hibernate Properties
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# 6. Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}

# 7. Feign Client Logging
logging.level.com.hospital.management.doctorservice.client=DEBUG
logging.file.path=./logs

# 8. Suppress Spring Cloud version mismatch warnings
spring.cloud.compatibility-verifier.enabled=false

# 9. Swagger / OpenAPI Documentation
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=false


logging.level.org.springframework.jdbc.datasource.init=DEBUG