


#APPLICATION
spring.application.name=patientservice
server.port=8081

#DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/patient_profile_management_db
spring.datasource.password=root
spring.datasource.username=root
spring.datasource.classDriverName=com.jdbc.cj.mysql.Driver

#SPRING DATA JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type=trace

#eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/